

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Maps/FPS_GameplayMap_1.FPS_GameplayMap_1
LocalMapOptions=
TransitionMap=/Game/Maps/FPS_TransitionMap.FPS_TransitionMap
bUseSplitscreen=True
TwoPlayerSplitscreenLayout=Horizontal
ThreePlayerSplitscreenLayout=FavorTop
FourPlayerSplitscreenLayout=Grid
bShowAllPlayerWidgetsWhenSplitscreenDisabled=False
bOffsetPlayerGamepadIds=False
GameInstanceClass=/Script/Engine.GameInstance
GameDefaultMap=/Game/Maps/FPS_MainMenuMap.FPS_MainMenuMap
ServerDefaultMap=/Engine/Maps/Entry.Entry
GlobalDefaultGameMode=/Script/Engine.GameMode
GlobalDefaultServerGameMode=None

[/Script/Engine.RendererSettings]
r.AllowStaticLighting=False

r.GenerateMeshDistanceFields=True

r.DynamicGlobalIlluminationMethod=1

r.ReflectionMethod=1

r.SkinCache.CompileShaders=True

r.RayTracing=True

r.RayTracing.RayTracingProxies.ProjectEnabled=True

r.Substrate=True

r.Substrate.ProjectGBufferFormat=0

r.Shadow.Virtual.Enable=1

r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True

r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8

r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6
-D3D11TargetedShaderFormats=PCD3D_SM5
+D3D11TargetedShaderFormats=PCD3D_SM5
Compiler=Default
AudioSampleRate=48000
AudioCallbackBufferFrameSize=1024
AudioNumBuffersToEnqueue=1
AudioMaxChannels=0
AudioNumSourceWorkers=4
SpatializationPlugin=
SourceDataOverridePlugin=
ReverbPlugin=
OcclusionPlugin=
CompressionOverrides=(bOverrideCompressionTimes=False,DurationThreshold=5.000000,MaxNumRandomBranches=0,SoundCueQualityIndex=0)
CacheSizeKB=65536
MaxChunkSizeOverrideKB=0
bResampleForDevice=False
MaxSampleRate=48000.000000
HighSampleRate=32000.000000
MedSampleRate=24000.000000
LowSampleRate=12000.000000
MinSampleRate=8000.000000
CompressionQualityModifier=1.000000
AutoStreamingThreshold=0.000000
SoundCueCookQualityIndex=-1

[/Script/LinuxTargetPlatform.LinuxTargetSettings]
-TargetedRHIs=SF_VULKAN_SM5
+TargetedRHIs=SF_VULKAN_SM6

[/Script/MacTargetPlatform.MacTargetSettings]
-TargetedRHIs=SF_METAL_SM5
+TargetedRHIs=SF_METAL_SM6

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/WorldPartitionEditor.WorldPartitionEditorSettings]
CommandletClass=Class'/Script/UnrealEd.WorldPartitionConvertCommandlet'

[/Script/Engine.UserInterfaceSettings]
bAuthorizeAutomaticWidgetVariableCreation=False
FontDPIPreset=Standard
FontDPI=72

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/FPS_Multiplayer")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_Blank",NewGameName="/Script/FPS_Multiplayer")
GameViewportClientClassName=/Script/CommonUI.CommonGameViewportClient

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=E1826D63406869F719EC3F9443D1C350
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

[/Script/Engine.GameEngine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/SteamSockets.SteamSocketsNetDriver",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")
; NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/SteamSockets.SteamSocketsNetDriver",DriverClassNameFallback="/Script/SteamSockets.SteamNetSocketsNetDriver")

[OnlineSubsystem]
DefaultPlatformService=Steam

[OnlineSubsystemSteam]
bEnabled=true
SteamDevAppId=480
bUsesPresence=true
bUseLobbiesIfAvailable=true
bInitServerOnClient=true
bUseSteamNetworking=true
bAllowP2PPacketRelay=true

; If using Sessions
bInitServerOnClient=true

[/Script/OnlineSubsystemSteam.SteamNetDriver]
NetConnectionClassName="OnlineSubsystemSteam.SteamNetConnection"


[CoreRedirects]
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSAnimInstance.MovementDirection",NewName="/Script/FPS_Multiplayer.FPSAnimInstance.LocomotionDirection")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSAnimInstance.WalkAnimSpeed",NewName="/Script/FPS_Multiplayer.FPSAnimInstance.WalkSpeed")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSAnimInstance.RunAnimSpeed",NewName="/Script/FPS_Multiplayer.FPSAnimInstance.RunSpeed")
+StructRedirects=(OldName="/Script/FPS_Multiplayer.CharacterLayers",NewName="/Script/FPS_Multiplayer.CharacterLayerStates")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSPlayerController.HUDWidget",NewName="/Script/FPS_Multiplayer.FPSPlayerController.HUDWidgetInstance")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSAnimInstance.AimInterpSpeed",NewName="/Script/FPS_Multiplayer.FPSAnimInstance.AimToInterpSpeed")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSAnimInstance.ToAimInterpSpeed",NewName="/Script/FPS_Multiplayer.FPSAnimInstance.PitchPerBoneInterpSpeed")
+ClassRedirects=(OldName="/Script/FPS_Multiplayer.InteractionComponent",NewName="/Script/FPS_Multiplayer.FPSInteractionComponent")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSWeaponData.FireMontage",NewName="/Script/FPS_Multiplayer.FPSWeaponData.AimedFireMontage")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSWeaponData.FireMontageAimed",NewName="/Script/FPS_Multiplayer.FPSWeaponData.AimedFireMontage")
+FunctionRedirects=(OldName="/Script/FPS_Multiplayer.FPSPlayerCharacter.GetGaitLayerState",NewName="/Script/FPS_Multiplayer.FPSPlayerCharacter.GetGaitState")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSHUD.HUDWidgetController",NewName="/Script/FPS_Multiplayer.FPSHUD.OverlayWidgetController")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSHUD.HUDWidgetControllerClass",NewName="/Script/FPS_Multiplayer.FPSHUD.OverlayWidgetControllerClass")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSHUD.HUDWidgetClass",NewName="/Script/FPS_Multiplayer.FPSHUD.OverlayWidgetClass")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSHUD.HUDWidget",NewName="/Script/FPS_Multiplayer.FPSHUD.OverlayWidget")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSHUD.OverlayController",NewName="/Script/FPS_Multiplayer.FPSHUD.OverlayWidgetController")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSHUD.OverlayControllerClass",NewName="/Script/FPS_Multiplayer.FPSHUD.OverlayWidgetControllerClass")
+PropertyRedirects=(OldName="/Script/FPS_Multiplayer.FPSCombatComponent.OnWeaponEquippedDelegate",NewName="/Script/FPS_Multiplayer.FPSCombatComponent.OnWeaponEquipped")

[/Script/Engine.VirtualTexturePoolConfig]
DefaultSizeInMegabyte=64
bPoolAutoGrowInEditor=True
+Pools=(Formats=(PF_DXT5,PF_DXT5),MinTileSize=520,MaxTileSize=520,SizeInMegabyte=207,bEnableResidencyMipMapBias=False,ResidencyMipMapBiasGroup=0,bAllowSizeScale=False,MinScaledSizeInMegabyte=0,MaxScaledSizeInMegabyte=0)

